# Generated by Django 3.1.3 on 2021-11-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_auto_20211121_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accno',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
