# Generated by Django 3.1.3 on 2021-11-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_auto_20211121_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
