# Generated by Django 3.1.3 on 2021-11-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_auto_20211121_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
