# Generated by Django 3.1.3 on 2021-11-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_remove_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
